name: Build

on:
  push:
    branches: [ '**' ]
    tags-ignore: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test
      - name: Publish locally
        run: unset CI && ./gradlew publishToMavenLocal
      - name: Test example project with gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: example
          arguments: build
          gradle-executable: gradlew
      - name: Test example project with maven
        run: cd example && mvn --batch-mode --update-snapshots package
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test check -PrunAllTests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

