name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test
      - name: Extract release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Publish release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEYID: ${{ secrets.SIGN_KEYID }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

